export const POST_USER = 'POST_USER';
export const REMOVE_USER = 'REMOVE_USER';

export const POST_BUSINESS_AREA = 'POST_BUSINESS_AREA';
export const GET_BUSINESSES_AREAS = 'GET_BUSINESSES_AREAS';
export const DELETE_BUSINESS_AREA = 'DELETE_BUSINESS_AREA';
export const UPDATE_BUSINESS_AREA = 'UPDATE_BUSINESS_AREA';

export const POST_CALENDAR_DATA = 'POST_CALENDAR_DATA';
export const GET_CALENDAR_DATA_PER_BUSINESSAREA = 'GET_CALENDAR_DATA_PER_BUSINESSAREA';
